// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_log from "./routes/api/log.ts";
import * as $index from "./routes/index.tsx";
import * as $form from "./islands/form.tsx";
import * as $logs from "./islands/logs.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/log.ts": $api_log,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/form.tsx": $form,
    "./islands/logs.tsx": $logs,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
